### ISSUE TITLE
What languages ​​does this support?

### ISSUE THREAD

**Issue by AlexisPradoLucero** [stephenswetonic/ytpai#1]
I would like to know which languages are supported

**Comment by AlexisPradoLucero** [comment]
I would like it to work for the Spanish language

**Comment by stephenswetonic** [comment]
Oh right, at the moment it's English only. I could add some more models and add a dropdown menu for that.

**Comment by stephenswetonic** [comment]
Added models for Spanish, French, German, and Russian.
