### ISSUE TITLE
Server is currently down

### ISSUE THREAD

**Issue by freakwaves** [stephenswetonic/ytpai#11]
Hi, I wanted to try the app but it has been displaying the message "The server is currently down. Please try again later." for at least 3 days. Also, any plans/ possibility for a local version? it seems like it would be a fun tool. Thanks.

**Comment by stephenswetonic** [comment]
Hello! Sorry about the outage. I run the AI server from home and had a power outage. I could put something together to make the server and client local. It uses AWS too, but that isn't strictly needed either.

**Comment by stephenswetonic** [comment]
I made another repo for this local version, check it out! Just made it so hopefully the installation steps and everything are good. I may make an install script at some point.

https://github.com/stephenswetonic/sentencemixerai
