### ISSUE TITLE
Audio or video doesn't load

### ISSUE THREAD

**Issue by Gonzaluigi** [stephenswetonic/ytpai#2]
Help me. When I click to "analyze", the **audio** or **video** doesn't load and it **stucks** on loading.

Any fix or something for the issue?

Here's the issue screenshot.
![Screenshot_20231125-173152~2](https://github.com/stephenswetonic/ytpai/assets/80421140/2f2c1154-a196-46da-892a-2f1b261afc6f)

**Comment by stephenswetonic** [comment]
Unfortunately I had to take the server offline due to the costs and haven't updated the info here. I may look for a new way of setting up the server.

**Comment by Gonzaluigi** [comment]
Okay, I will stay tuned.

**Comment by chippyman888** [comment]
> Unfortunately I had to take the server offline due to the costs and haven't updated the info here. I may look for a new way of setting up the server.

you really should say that on the site so other know, i spent an hour trying to figure out what was wrong before i saw this

**Comment by stephenswetonic** [comment]
> > Unfortunately I had to take the server offline due to the costs and haven't updated the info here. I may look for a new way of setting up the server.
> 
> you really should say that on the site so other know, i spent an hour trying to figure out what was wrong before i saw this

This is a project done in my free time with a limited budget. Though I'm happy to say the functionality will be returned very soon thanks to a new backend.
