### ISSUE TITLE
Does this support chrome moblie?

### ISSUE THREAD

**Issue by cgk836** [stephenswetonic/ytpai#6]
hi, does this support mobile or nah because?
![Screenshot_20240619_063612_Chrome](https://github.com/stephenswetonic/ytpai/assets/173269526/95a1721e-b782-4e59-bd5b-782103b59f76)

**Comment by stephenswetonic** [comment]
I haven't tested on mobile browsers. The drag and drop ui should work on mobile now. What format is the video? I would highly recommend using the site on desktop for easier use.

**Comment by stephenswetonic** [comment]
Go ahead and try again, please. I just fixed a bug in the new UI.
