### ISSUE TITLE
....why the video don't load?

### ISSUE THREAD

**Issue by zumzum360** [stephenswetonic/ytpai#7]
well..... why the video is not loading even though i made some sentence mixings

**Comment by stephenswetonic** [comment]
Can you help me by answering some questions? Were the words successfully analyzed? You dragged the desired words to the "words to mix" section and clicked generate? Then no generated video showed up?

**Comment by stephenswetonic** [comment]
Alright, I noticed issues with the new UI not properly recognizing what's inside "words to mix" 

In some cases it thinks there's nothing there, in some cases it gets the words wrong. Very weird, sorry!

**Comment by stephenswetonic** [comment]
There was a bug with dragging single words without selecting them. It's working as expected now 👍🏻

**Comment by zumzum360** [comment]
well... i dragged some words and i generated the video, and it does not load

**Comment by stephenswetonic** [comment]
> well... i dragged some words and i generated the video, and it does not load

Did you try again? I pushed out a fix last night.

**Comment by zumzum360** [comment]
it does work now
