### ISSUE TITLE
Words dragged from "Matched words" are ignored

### ISSUE THREAD

**Issue by Dixions** [stephenswetonic/ytpai#9]
If you drag Words from "Matched Words" to "Words to mix", they are ignored,

https://github.com/user-attachments/assets/5b234ec5-8fd1-46f9-9bbe-eb5d62243dc0

**Comment by stephenswetonic** [comment]
Can you link the video you used? I can see what happened here. The model generates timestamps for each word, so they are prone to bad detections.

**Comment by Dixions** [comment]
> Can you link the video you used? I can see what happened here. The model generates timestamps for each word, so they are prone to bad detections.

This is a test video I made to show the problem. It happens with any source. Anyways, this is that video:

https://github.com/user-attachments/assets/a65f881e-671c-489b-9bfb-bcbc9bb25ac9

**Comment by stephenswetonic** [comment]
Thanks for providing that and for bringing up the issue! I must have not tested that case. It's fixed now. A couple other things I did:
- You can hit enter to filter the words now
- Filtering will actually clear out what was already there
- You can see the highlighted text in the search field
